### ISSUE TITLE
又遇到了一个棘手的bug

### ISSUE THREAD

**Issue by xiaogaofudao** [Blincheng/EToast2#3]
基于最新版的 eToast，如果context 传递 getApplicationContext() 程序会闪退， params.type 加上 TYPE_HOST 程序不闪退。又回到 魅族，小米 个别机型不弹出的 情况。
去掉 params.type 传递 Activity 的 context 正常。

闪退时报错信息，
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                                 at android.view.ViewRootImpl.setView(ViewRootImpl.java:700)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:289)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                 at com.gaogeek.toast.Toast.show(Toast.java:72)
                                                                 at com.hsc.pcddd.utils.ToastUtil$1.run(ToastUtil.java:80)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

感觉很尴尬，封装 eToast 的时候，传递 BaseApplication.getInstance().getApplicationContext() 时候发现的。这样调用 只需要 ToastUtil.show("消息") 不需要 传递 当前的 Activity.this 了。

**Comment by Blincheng** [comment]
那就舍弃对Application的支持吧，毕竟Toast是和用户的交互提示，在Application中一般是不会去处理用户交互的。如果有需要弹出Toast的地方，想必肯定也有上下文。

**Comment by xiaogaofudao** [comment]
搞了好久，准备放弃，奇怪的是  原生 Toast 可以支持 apllication 的 上下文。直觉是  type 的 类型关系。不过系统源码没办法追踪了

**Comment by Blincheng** [comment]
系统用的就是
TN() {
            // XXX This should be changed to use a Dialog, with a Theme.Toast
            // defined that sets up the layout params appropriately.
            final WindowManager.LayoutParams params = mParams;
            params.height = WindowManager.LayoutParams.WRAP_CONTENT;
            params.width = WindowManager.LayoutParams.WRAP_CONTENT;
            params.format = PixelFormat.TRANSLUCENT;
            params.windowAnimations = com.android.internal.R.style.Animation_Toast;
            params.type = WindowManager.LayoutParams.TYPE_TOAST;
            params.setTitle("Toast");
            params.flags = WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON
                    | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                    | WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE;
        }

**Comment by xiaogaofudao** [comment]
这个可以看到。可以 看到 系统如何 处理  type 类型值的么

**Comment by Aronlong1001** [comment]
params.type加上TYPE_TOAST不弹出是不是只在安卓7.1.1及以上版本出现？7.1.1之后google对悬浮窗做了限制。

**Comment by xiaogaofudao** [comment]
应该不是。魅族pro6 flyme6 安卓6.0 的 就不弹出。魅蓝flyme6 不过是 安卓 5.1 的就可以。小米note miui8 安卓 6.0 也是不弹出。红米同样版本 就能弹出。应该是有些 rom 做了单独处理。android 窗口机制这一块 感觉是个 黑盒子，不知道内部如何处理的，静等大神研究 系统Toast 为何可以使用 application 上下文

**Comment by xiaogaofudao** [comment]
今天下午突然有个灵感，通过反射show hide 解决 Toast 不能使用 application 的上下文。目前经过测试可以绕过所有系统通知权限正常显示，包括 魅族pro6, 小米 note 这两个坑的机型。特此分享给 大家。Toast 
的学习就此告一段落。多谢 @Blincheng  的热心解答，帮助我这个小白 一步步成长。

**Comment by Blincheng** [comment]
你的代码呢？

**Comment by xiaogaofudao** [comment]
https://github.com/xiaogaofudao/Android-Widget
这个项目 toast module

**Comment by zimo2013** [comment]
@xiaogaofudao tks, resolve my problem!

**Comment by 506967734** [comment]
华为手机也遇到这样问题
