### ISSUE TITLE
通知关闭，context 传入 applicationContext,导致程序崩溃

### ISSUE THREAD

**Issue by amibition521** [Blincheng/EToast2#8]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                                 at android.view.ViewRootImpl.setView(ViewRootImpl.java:908)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
                                                                 at com.bajiao.video.widget.EToast2.show(EToast2.java:82)
                                                                 at com.bajiao.video.widget.CustomToast.show(CustomToast.java:60)
                                                                 at com.bajiao.video.util.ToastUtil.showDefaultToast(ToastUtil.java:65)
                                                                 at com.bajiao.video.util.ToastUtil.showShortToast(ToastUtil.java:31)
                                                                 at com.bajiao.video.play.FragmentPlay$18.handleMessage(FragmentPlay.java:721)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by Blincheng** [comment]
已经更新到2.2.0，支持Application，不过底层上还是用的当前的Activity
